### ISSUE TITLE
Same package name

### ISSUE THREAD

**Issue by markfairbanks** [hope-data-science/tidydt#1]
I have a favor to ask - would you mind changing the name of your package? I have a `tidydt` package with 67 stars on GitHub that I'm currently prepping for a CRAN submission. It would be nice to avoid future confusion, especially since they have such similar goals.

I realize I technically don't have "dibs" on a package name, but I've already spent time communicating this package to the rstats community, and have been developing it since November. It's functionality is quite extensive and is also `rlang` compatible, which will be an easy transition for current tidyverse users.

See here: https://github.com/markfairbanks/tidydt

**Comment by hope-data-science** [comment]
Thank you for noting, but I have submitted to CRAN already, in last month! And I am struggling with the debugging part all the way these days. This work starts once we have known `maditr`, but did no released until we got a stable version.

Currently, lots of our research work is built upon this package, and lots of documents is based on it (we acutually need this functionalities very much, and we need it the way it is now). Therefore, could you do us a flavor to change the name? Thanks.
